### ISSUE TITLE
住信SBI 銀行口座問い合わせ

### ISSUE THREAD

**Issue by in-the-box** [pixelgram/project#12]
進捗を問い合わせてください

**Comment by masakisaaan** [comment]
報告  

住信SBI銀行の法人口座開設状況について

問い合わせたところ、
18日に書類受理。
以降は担当者が順に審査中とのこと。

年内に審査が通っても口座開設が完了するかは不明。
審査が完了次第代表者メールアドレス宛と本店所在地の住所宛に連絡がくる予定。

以上
